apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2rayn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2rayn
  template:
    metadata:
      labels:
        app: v2rayn
    spec:
      containers:
      - image: okteto.dev/ray:latest
        name: v2rayn
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/Tuxedo-html.zip"
        - name: Vless_UUID
          value: "1a8e2717-a972-4879-9edb-cccaf5b67cb9"
        - name: Vless_Path
          value: "/app"
        - name: Vmess_UUID
          value: "1a8e2717-a972-4879-9edb-cccaf5b67cb9"
        - name: Vmess_Path
          value: "/vmess"
        - name: Share_Path
          value: "/crtbnmiirtr"
